# Generated by Django 3.2 on 2021-05-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollmodel',
            name='polls',
        ),
        migrations.AddField(
            model_name='pollmodel',
            name='downvotes',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='pollmodel',
            name='upvotes',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
